### ISSUE TITLE
Unable to install Plugin in DBeaver

### ISSUE THREAD

**Issue by jeffsanicola** [premium-minds/dbeaver-vault#15]
Hello,

I'm interested in trying out this plugin but I'm having difficulty getting it installed with the following error:

```
Unable to read repository at https://raw.githubusercontent.com/premium-minds/dbeaver-vault/master/update-site/content.xml.
Unable to read repository at https://raw.githubusercontent.com/premium-minds/dbeaver-vault/master/update-site/content.xml.
No route to host
```

I'm running DBeaver CE 23.1.2 on MacOS (arm64) installed via `brew`.

To replicate
1. Open DBeaver from Applications menu
2. Go to Help -> Install New Software...
3. In the `Work with:` field I enter "https://raw.githubusercontent.com/premium-minds/dbeaver-vault/master/update-site/"
4. The above error is returned

I did run through the Optional Extensions link and was able to successfully resolve the https://dbeaver.io/update/office/latest/ extension.

Any help that can be provided would be much appreciated.
Thanks!

**Comment by froque** [comment]
`No route to host` is a DNS or network issue. can you open the link in a browser or with curl ? maybe try again later. not much that we can do.

**Comment by jeffsanicola** [comment]
Hi @froque,

Apologies for the delayed response. When I try to access the file mentioned in the error via curl I get a 404 message.

```bash
#> curl https://raw.githubusercontent.com/premium-minds/dbeaver-vault/master/update-site/content.xml
404: Not Found
```

Similarly, when I browse the repo and the raw files I do not see `update-site/content.xml` as an existing file. There is a `update-site/content.jar` but DBeaver doesn't seem to be interested in that one.

If I do the same for the `README.md` file, in the root of the repo, that loads without issue.

It may be worth noting that DBeaver is automatically appending the `content.xml` file name when I paste in the URL from the instructions and there doesn't appear to be a way to tell it not to do that,  nor can I point to a different file.

**Comment by jeffsanicola** [comment]
OK, so I don't know what I did but it started working after a few more attempts and messing with proxy certificates.
