### ISSUE TITLE
Caching Connections

### ISSUE THREAD

**Issue by jacobpinney-ds** [premium-minds/dbeaver-vault#17]
Error:
When invalidating/re-connecting to an old connection, new credentials will not be fetched. This results in a failed login attempt. 

```FATAL: password authentication failed for user "[redacted]"```

Steps to reproduce:
- Use Vault Plugin in DBeaver and open a connection
- Wait until the credential expire for said connection
- Get a new vault token
- Invalidate the connection and try to re-connect
- Error appears

Workaround:
- Restart DBeaver

Machine Details:
- Windows 10
- DBeaver v24.1.0
- Vault Plugin v1.0.0.202301041433

**Comment by froque** [comment]
Could not reproduce it. Can you try again or share extra information ?

**Comment by jacobpinney-ds** [comment]
Another piece of information that may play into this issue is the Token file. Usually when the credentials expire, so has the token file. So, there is a 3rd step of updating the token file with a new value.

I have also noticed that DBeaver 24.1.0 is caching some items around connections. For example, I usually have to MFA for SSH but when I am connection and "Test tunnel configuration", it doesn't prompt me additionally. Is it possible DBeaver 24.1.0 introduced logic to cache items that cause this issue with the Vault Plugin?

**Comment by jacobpinney-ds** [comment]
Each time the password authentication fails, the user given remains the same. It's like it doesn't know that the user/pass failed and it tries with the same credentials. It all seems like some sort of cache issue, especially since restarting dbeaver clears the issue.

**Comment by froque** [comment]
Thanks for the report. I was able to reproduce it. The caching was intentional (#12). #19 should fix the problem.

**Comment by jacobpinney-ds** [comment]
I am no longer experiencing this error - thanks for fixing it so quick!
